# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18984794e85de16e6621a9c6ff13cbc28fc84c0504adf70f482773e4bc27fe290c6978344bac60f7ec3c03133458d0147200f5f9253707036954249d7b862ceb

test:
  secret_key_base: 1ce6288cd71575fafafa0d00c4f6435a3de3dd1de55a405af89c66b17ee948f98096ec6abae3f60259c8db442af3102f329276fd46b5fb594e0d0559fc1abffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
